# Generated by Django 5.0.4 on 2024-06-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gakuseikanri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
                ('enumber', models.CharField(max_length=15)),
                ('eemail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'gakuseikanri',
            },
        ),
    ]
