# Generated by Django 5.0.4 on 2024-06-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gakuseikanri', '0002_rename_id_student_student_id_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
