# Generated by Django 5.0.4 on 2024-06-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gakuseikanri', '0003_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='employee',
        ),
    ]
