# Generated by Django 5.0.4 on 2024-06-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gakuseikanri', '0004_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
